spring:
  profiles:
    include: oauth2, jwt, swagger

  messages:
    basename: errors

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

  redis:
    port: 6379
    host: localhost

logging:
  level:
    org.hibernate.SQL: debug
